-- VHDL Entity hdlclib.agent_hdlc.symbol
--
-- Created:
--          by - harry.UNKNOWN (IBIZA)
--          at - 21:25:19 15/11/2025
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2017.1a (Build 5)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY agent_hdlc IS
   PORT( 
      miso : IN     std_logic;
      mosi : OUT    std_logic
   );

-- Declarations

END agent_hdlc ;

--
-- VHDL Architecture hdlclib.agent_hdlc.struct
--
-- Created:
--          by - harry.UNKNOWN (IBIZA)
--          at - 21:42:53 15/11/2025
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2017.1a (Build 5)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF agent_hdlc IS

   -- Architecture declarations
   type t_buffer is array (0 to 16384) of std_logic;

   -- Internal signal declarations
   SIGNAL clk   : std_logic;
   SIGNAL rst_n : std_logic;


  signal miso_buffer: t_buffer := (others => '1');
  signal mosi_buffer: t_buffer := (others => '1');

   signal addr_mosi: integer;
   signal addr_miso: integer;

   signal cnt_mosi: integer;
   signal cnt_miso: integer;

   signal rx_enable: std_logic;

   signal shift_miso: std_logic_vector(7 downto 0);
   signal shift_mosi: std_logic_vector(7 downto 0);


BEGIN
   -- Architecture concurrent statements
   -- HDL Embedded Text Block 1 p_mosi
   p_txbuffer : process (clk, rst_n)
   begin
       if (rst_n = '0') then
           mosi      <= '1';
           addr_mosi <= 0;
           cnt_mosi  <= 0;
       elsif rising_edge(clk) then
   
           if (cnt_mosi > 0) then
               mosi      <= mosi_buffer(addr_mosi);
               addr_mosi <= addr_mosi + 1;
               cnt_mosi  <= cnt_mosi - 1;
           else 
               mosi <= '1';
           end if;
   
       end if;
   end process p_txbuffer;

   -- HDL Embedded Text Block 2 p_miso
   p_flag_detect : process (clk, rst_n)
   begin
       if rst_n = ('0') then
           shift_miso <= (others => '0');
           rx_enable  <= '0';
       elsif falling_edge(clk) then
   
           shift_miso <= shift_miso(6 downto 0) & miso;
   
           -- Detectar flag HDLC 0x7E = "01111110"
           if (shift_miso(6 downto 0) = "0111111" and miso = '0' and rx_enable = '0') then
               rx_enable <= '1';
               -- Detectar flag HDLC 0x7E = "01111110"
           elsif (shift_miso(6 downto 0) = "0111111" and miso = '0' and rx_enable = '1') then
               rx_enable <= '0';
           end if;
   
       end if;
   end process p_flag_detect;
   
   p_rxbuffer : process (clk, rst_n)
   begin
       if (rst_n = '0') then
           addr_miso <= 0;
           cnt_miso  <= 0;
       elsif falling_edge(clk) then
           if (rx_enable = '1') then
               miso_buffer(addr_miso) <= shift_miso(7);
               addr_miso              <= addr_miso + 1;
               cnt_miso               <= 7;
           elsif (cnt_miso > 0) then
               miso_buffer(addr_miso) <= shift_miso(7);
               addr_miso              <= addr_miso + 1;
               cnt_miso               <= cnt_miso - 1;
           end if;
       end if;
   end process p_rxbuffer;

   -- HDL Embedded Text Block 3 p_system
   clk <= not(clk) after 250 ns;
   rst_n <= '0', '1' after 33 ns;


   -- Instance port mappings.

END struct;
