-- VHDL Entity hdlc.setup_recovery_clk.symbol
--
-- Created:
--          by - harry.UNKNOWN (IBIZA)
--          at - 17:16:56 26/10/2025
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2021.4 Built on 12 Oct 2021 at 20:47:32
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;

ENTITY setup_recovery_clk IS
   PORT( 
      freq_tick : OUT    std_logic
   );

-- Declarations

END setup_recovery_clk ;

--
-- VHDL Architecture hdlc.setup_recovery_clk.beh
--
-- Created:
--          by - harry.UNKNOWN (IBIZA)
--          at - 17:17:10 26/10/2025
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2021.4 Built on 12 Oct 2021 at 20:47:32
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;

LIBRARY hdlc;

ARCHITECTURE beh OF setup_recovery_clk IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL clk   : std_logic := '0';
   SIGNAL rst_n : std_logic := '0';
   SIGNAL rx    : std_logic;


   -- Component Declarations
   COMPONENT recover_clk
   PORT (
      clk       : IN     std_logic ;
      rst_n     : IN     std_logic ;
      rx        : IN     std_logic ;
      freq_tick : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : recover_clk USE ENTITY hdlc.recover_clk;
   -- pragma synthesis_on


BEGIN
   -- Architecture concurrent statements
   -- HDL Embedded Text Block 1 p_stimuli
   -- p_stimuli
   rst_n <= '0', '1' after 2.1 ns;
   clk  <= not(clk) after 1 ns;
   
   rx <= '1', '0' after 100 ns, '1' after 600 ns, '0' after 1100 ns, '1' after 1592 ns;  


   -- Instance port mappings.
   i_dut : recover_clk
      PORT MAP (
         clk       => clk,
         rst_n     => rst_n,
         rx        => rx,
         freq_tick => freq_tick
      );

END beh;
